# Generated by Django 6.0.3 on 2026-05-23 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_accounting_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyjoinrequest',
            name='requested_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_requests', to='core.branch'),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='core.branch'),
        ),
    ]
