# Generated by Django 6.0.3 on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_subscriptionplan_max_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='calendar_preference',
            field=models.CharField(choices=[('gregorian', 'ميلادي'), ('hijri', 'هجري')], default='gregorian', max_length=20),
        ),
    ]
