# Generated by Django 6.0.3 on 2026-05-23 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_calendar_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='branch_access',
            field=models.CharField(choices=[('all', 'كل فروع الشركة'), ('single', 'فرع واحد فقط')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='national_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='رقم الهوية'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role', verbose_name='الدور'),
        ),
    ]
