# Generated by Django 6.0.3 on 2026-05-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
    ]
