# Generated by Django 6.0.3 on 2026-05-21 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_invoice_payment_method_invoice_zatca_hash_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseinvoice',
            options={'permissions': [('import_ai_invoice', 'إضافة فاتورة بالذكاء الاصطناعي'), ('view_ai_insights', 'عرض نصائح وتوقعات الذكاء الاصطناعي')]},
        ),
    ]
